/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.holovchenkoa.plugin1

import com.holovchenkoa.plugin1.extension.ServerConfigurationExtension
import com.holovchenkoa.plugin1.task.ExportServersTask
import com.holovchenkoa.plugin1.task.ListClustersTask
import org.gradle.api.NamedDomainObjectContainer
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 *
 */
class ServerConfigurationPlugin: Plugin<Project> {
    override fun apply(project: Project) {

        val clusters: NamedDomainObjectContainer<Cluster> = project.container(Cluster::class.java)
        project.extensions.add("clusters", clusters)

        val serversExtension = project.extensions.create("serversConfiguration", ServerConfigurationExtension::class.java)

        clusters.whenObjectAdded {cluster ->
            // use org.gradle.logging.level=info in gradle.properties to see these logs
            project.logger.info("Cluster added: $cluster")
        }
        serversExtension.servers.whenObjectAdded {server ->
            project.logger.info("Server added: $server")
        }

        // Register a task
        project.tasks.register("listClusters", ListClustersTask::class.java).configure {
            it.group = "servers"
            it.clusters = clusters
            it.clusterNodes = serversExtension.servers
        }
        project.tasks.register("exportServers", ExportServersTask::class.java).configure {
            it.group = "servers"
//            it.servers.set(project.objects.listProperty(String::class.java).convention(serversExtension.servers.map { "${it.name}:${it.port}" }))
            it.servers.set(serversExtension.servers.map { "${it.name}:${it.port.get()}" })
        }
    }
}
